'use client';

import { useState, useRef, useEffect, useCallback } from 'react';
import type { NewsArticle } from '@/lib/types';
import { motion, AnimatePresence } from 'framer-motion';
import { Sparkles, AlertTriangle, RefreshCw, ChevronRight, Volume2, VolumeX } from 'lucide-react';

interface Props {
  articles: NewsArticle[];
}

interface Digest {
  summary: string;
  keyEvents: string[];
  riskAssessment: string;
  generatedAt: string;
}

const COOLDOWN_SECONDS = 30; // Minimum time between requests in seconds

export default function AIDigest({ articles }: Props) {
  const [digest, setDigest] = useState<Digest | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [cooldownRemaining, setCooldownRemaining] = useState(0);
  const [speaking, setSpeaking] = useState(false);

  const playBriefing = useCallback(() => {
    if (!digest || typeof window === 'undefined' || !window.speechSynthesis) return;
    window.speechSynthesis.cancel();
    const script = `${digest.summary}. Key events: ${digest.keyEvents.join('. ')}. Risk assessment: ${digest.riskAssessment}`;
    const utt = new SpeechSynthesisUtterance(script);
    utt.rate = 0.92;
    utt.pitch = 0.85;
    const voices = window.speechSynthesis.getVoices();
    utt.voice = voices.find(v => v.lang.startsWith('en')) ?? null;
    utt.onend = () => setSpeaking(false);
    utt.onerror = () => setSpeaking(false);
    setSpeaking(true);
    window.speechSynthesis.speak(utt);
  }, [digest]);

  const stopBriefing = useCallback(() => {
    window.speechSynthesis?.cancel();
    setSpeaking(false);
  }, []);
  const lastRequestTime = useRef<number>(0);
  const isRequestInProgress = useRef<boolean>(false);
  const cooldownInterval = useRef<NodeJS.Timeout | null>(null);
  const autoGenerateTimeout = useRef<NodeJS.Timeout | null>(null);
  const hasAutoGenerated = useRef<boolean>(false);

  const generate = useCallback(async () => {
    // Prevent if already loading
    if (isRequestInProgress.current || loading) {
      return;
    }

    // Check cooldown
    const now = Date.now();
    const timeSinceLastRequest = (now - lastRequestTime.current) / 1000;
    
    if (timeSinceLastRequest < COOLDOWN_SECONDS) {
      const remaining = Math.ceil(COOLDOWN_SECONDS - timeSinceLastRequest);
      setCooldownRemaining(remaining);
      return;
    }

    // Prevent multiple simultaneous requests
    isRequestInProgress.current = true;
    setLoading(true);
    setError(null);
    setCooldownRemaining(0);

    try {
      const res = await fetch('/api/ai-digest', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ articles }),
      });
      if (!res.ok) {
        const e = await res.json();
        throw new Error(e.error || 'AI service unavailable');
      }
      const data = await res.json();
      setDigest(data);
      lastRequestTime.current = Date.now();
      setCooldownRemaining(COOLDOWN_SECONDS);
    } catch (err: any) {
      setError(err.message ?? 'Failed to generate digest');
    } finally {
      setLoading(false);
      isRequestInProgress.current = false;
    }
  }, [articles, loading]);

  // Auto-generate briefing when articles are available
  useEffect(() => {
    // Only auto-generate if we have articles, no digest yet, and haven't already tried
    if (articles.length > 0 && !digest && !loading && !hasAutoGenerated.current && !error) {
      // Debounce auto-generation by 2 seconds to avoid too many requests
      autoGenerateTimeout.current = setTimeout(() => {
        hasAutoGenerated.current = true;
        generate();
      }, 2000);
    }

    return () => {
      if (autoGenerateTimeout.current) {
        clearTimeout(autoGenerateTimeout.current);
      }
    };
  }, [articles.length, digest, loading, error, generate]);

  // Update cooldown timer
  useEffect(() => {
    if (cooldownRemaining > 0) {
      cooldownInterval.current = setInterval(() => {
        setCooldownRemaining((prev) => {
          if (prev <= 1) {
            if (cooldownInterval.current) {
              clearInterval(cooldownInterval.current);
              cooldownInterval.current = null;
            }
            return 0;
          }
          return prev - 1;
        });
      }, 1000);
    } else {
      if (cooldownInterval.current) {
        clearInterval(cooldownInterval.current);
        cooldownInterval.current = null;
      }
    }

    return () => {
      if (cooldownInterval.current) {
        clearInterval(cooldownInterval.current);
      }
    };
  }, [cooldownRemaining]);

  return (
    <div className="panel h-full flex flex-col">
      <div className="panel-header">
        <span className="flex items-center gap-2">
          <Sparkles size={12} className="text-[#ff8800]" />
          WCI INTELLIGENCE BRIEF
        </span>
        <span className="text-[8px] text-[#2a4a2a]">WCI</span>
      </div>

      <div className="flex-1 overflow-y-auto p-3">
        {!digest && !loading && !error && (
          <div className="flex flex-col items-center justify-center h-full gap-4 text-center py-8">
            <div className="text-[#3a6a4a] font-mono text-[11px] leading-relaxed max-w-xs">
              Gathering real-time intelligence briefing from {articles.length} articles...
            </div>
            <div className="flex gap-1">
              {[0, 1, 2].map(i => (
                <motion.div
                  key={i}
                  className="w-2 h-2 rounded-full bg-[#ff4400]"
                  animate={{ scale: [1, 1.4, 1] }}
                  transition={{ duration: 0.8, delay: i * 0.2, repeat: Infinity }}
                />
              ))}
            </div>
          </div>
        )}

        {loading && (
          <div className="flex flex-col items-center justify-center h-full gap-3">
            <div className="font-mono text-[11px] text-[#ff8800] animate-pulse tracking-widest">ANALYSING {articles.length} ARTICLES...</div>
            <div className="flex gap-1">
              {[0, 1, 2].map(i => (
                <motion.div
                  key={i}
                  className="w-2 h-2 rounded-full bg-[#ff4400]"
                  animate={{ scale: [1, 1.4, 1] }}
                  transition={{ duration: 0.8, delay: i * 0.2, repeat: Infinity }}
                />
              ))}
            </div>
          </div>
        )}

        {error && (
          <div className="flex flex-col items-center gap-3 py-8">
            <div className="text-[#ff2200] font-mono text-[11px] flex items-center gap-1">
              <AlertTriangle size={12} />
              {error}
            </div>
            <button 
              onClick={generate} 
              disabled={loading || cooldownRemaining > 0}
              className={`text-[9px] font-mono transition-colors ${
                loading || cooldownRemaining > 0
                  ? 'text-[#2a4a2a] cursor-not-allowed opacity-50'
                  : 'text-[#3a6a4a] hover:text-[#8aaa8a] cursor-pointer'
              }`}
            >
              {cooldownRemaining > 0 ? `RETRY IN ${cooldownRemaining}S` : 'RETRY'}
            </button>
          </div>
        )}

        <AnimatePresence>
          {digest && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="space-y-4 text-[11px] font-mono"
            >
              <div className="text-[9px] text-[#3a6a4a] tracking-widest mb-2">
                GENERATED {new Date(digest.generatedAt).toLocaleTimeString()} UTC
              </div>

              <div>
                <div className="text-[10px] text-[#ff8800] tracking-widest mb-2 flex items-center gap-1">
                  <Sparkles size={10} />
                  SITUATION OVERVIEW
                </div>
                <p className="text-[#7a9a7a] leading-relaxed">{digest.summary}</p>
              </div>

              {digest.keyEvents?.length > 0 && (
                <div>
                  <div className="text-[10px] text-[#ffcc00] tracking-widest mb-2 flex items-center gap-1">
                    <Sparkles size={10} />
                    KEY EVENTS
                  </div>
                  <ul className="space-y-2">
                    {digest.keyEvents.map((e, i) => (
                      <motion.li
                        key={i}
                        initial={{ opacity: 0, x: -8 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: i * 0.1 }}
                        className="flex gap-2 text-[#6a8a6a]"
                      >
                        <ChevronRight size={12} className="text-[#ff4400] flex-shrink-0" />
                        <span className="leading-relaxed">{e}</span>
                      </motion.li>
                    ))}
                  </ul>
                </div>
              )}

              {digest.riskAssessment && (
                <div className="border border-[#ff440033] bg-[#ff440011] rounded p-3">
                  <div className="text-[10px] text-[#ff4400] tracking-widest mb-2 flex items-center gap-1">
                    <Sparkles size={10} />
                    RISK ASSESSMENT
                  </div>
                  <p className="text-[#aa8866] leading-relaxed">{digest.riskAssessment}</p>
                </div>
              )}

              <div className="flex items-center gap-3 mt-2 flex-wrap">
                <button
                  onClick={generate}
                  disabled={loading || cooldownRemaining > 0}
                  className={`text-[9px] font-mono transition-colors ${
                    loading || cooldownRemaining > 0
                      ? 'text-[#2a4a2a] cursor-not-allowed opacity-50'
                      : 'text-[#3a6a4a] hover:text-[#5a8a6a] cursor-pointer'
                  }`}
                >
                  <RefreshCw size={10} className="inline mr-1" />
                  {cooldownRemaining > 0 ? `REFRESH IN ${cooldownRemaining}S` : 'REFRESH BRIEFING'}
                </button>
                {typeof window !== 'undefined' && 'speechSynthesis' in window && (
                  <button
                    onClick={speaking ? stopBriefing : playBriefing}
                    className={`text-[9px] font-mono transition-colors flex items-center gap-1 ${
                      speaking ? 'text-[#ff4400] animate-pulse' : 'text-[#44aa66] hover:text-[#66cc88]'
                    }`}
                  >
                    {speaking ? <VolumeX size={10} /> : <Volume2 size={10} />}
                    {speaking ? 'STOP' : 'READ BRIEFING'}
                  </button>
                )}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
