import type { ConflictZone, ConflictTag, Region } from './types';

// ── RSS Feed Sources ─────────────────────────────────────────────────
export const RSS_FEEDS = [
  {
    name: 'BBC World',
    url: 'https://feeds.bbci.co.uk/news/world/rss.xml',
    bias: 'center' as const,
    logo: '🇬🇧',
    region: 'Global' as Region,
  },
  {
    name: 'Al Jazeera',
    url: 'https://www.aljazeera.com/xml/rss/all.xml',
    bias: 'center-left' as const,
    logo: '🇶🇦',
    region: 'Middle East' as Region,
  },
  {
    name: 'Reuters World',
    url: 'https://feeds.reuters.com/reuters/worldNews',
    bias: 'center' as const,
    logo: '🌐',
    region: 'Global' as Region,
  },
  {
    name: 'The Guardian',
    url: 'https://www.theguardian.com/world/rss',
    bias: 'center-left' as const,
    logo: '🇬🇧',
    region: 'Global' as Region,
  },
  {
    name: 'DW News',
    url: 'https://rss.dw.com/xml/rss-en-world',
    bias: 'center' as const,
    logo: '🇩🇪',
    region: 'Global' as Region,
  },
  {
    name: 'RFI English',
    url: 'https://www.rfi.fr/en/rss',
    bias: 'center' as const,
    logo: '🇫🇷',
    region: 'Africa' as Region,
  },
  {
    name: 'France 24',
    url: 'https://www.france24.com/en/rss',
    bias: 'center' as const,
    logo: '🇫🇷',
    region: 'Global' as Region,
  },
];

// ── YouTube News Channels (channel RSS — no API key needed) ──────────
export const YT_CHANNELS = [
  { name: 'BBC News', channelId: 'UCnUYZLuoy1rq1aVMwx4aTzw', logo: '🇬🇧' },
  { name: 'Al Jazeera English', channelId: 'UCNye-wNBqNL5ZzHSJdnWBdw', logo: '🇶🇦' },
  { name: 'DW News', channelId: 'UCknLrEdhRCp1aegoMqRaCZg', logo: '🇩🇪' },
  { name: 'France 24 English', channelId: 'UCQfwfsi5VrQ8yKZ-UWmAEFg', logo: '🇫🇷' },
  { name: 'WION', channelId: 'UCEhMIer5UtYHEDEa57ETSSA', logo: '🇮🇳' },
  { name: 'TRT World', channelId: 'UC7fWeaHhqgM4Ry-RMpM2YYw', logo: '🇹🇷' },
];

// ── Live Conflict Zones ──────────────────────────────────────────────
export const CONFLICT_ZONES: ConflictZone[] = [
  {
    lat: 48.3794, lng: 31.1656,
    name: 'Ukraine–Russia War',
    country: 'Ukraine',
    severity: 9.5,
    type: 'war',
    tag: 'ukraine',
    casualties: '500,000+',
    startDate: '2022-02-24',
    description: 'Full-scale Russian invasion; largest land war in Europe since WWII.',
    factions: ['Ukraine', 'Russia'],
    relatedCountries: ['USA', 'NATO', 'Belarus', 'Poland'],
  },
  {
    lat: 31.35, lng: 34.3,
    name: 'Gaza War',
    country: 'Palestine',
    severity: 9.8,
    type: 'war',
    tag: 'gaza',
    casualties: '35,000+',
    startDate: '2023-10-07',
    description: 'Israeli military operation in Gaza following Hamas Oct 7 attack.',
    factions: ['Israel', 'Hamas', 'PIJ'],
    relatedCountries: ['USA', 'Iran', 'Qatar', 'Egypt', 'Jordan'],
  },
  {
    lat: 15.5, lng: 32.5,
    name: 'Sudan Civil War',
    country: 'Sudan',
    severity: 8.5,
    type: 'civil-war',
    tag: 'sudan',
    casualties: '15,000+',
    startDate: '2023-04-15',
    description: 'SAF vs RSF paramilitary forces; worst humanitarian crisis globally.',
    factions: ['SAF', 'RSF (Janjaweed)'],
    relatedCountries: ['UAE', 'Egypt', 'Ethiopia', 'Chad'],
  },
  {
    lat: 33.8869, lng: 35.5131,
    name: 'Lebanon–Israel Frontline',
    country: 'Lebanon',
    severity: 7.5,
    type: 'war',
    tag: 'lebanon',
    startDate: '2023-10-08',
    description: 'Hezbollah-Israel cross-border exchanges; risk of wider war.',
    factions: ['Hezbollah', 'IDF'],
    relatedCountries: ['Iran', 'Syria', 'Israel', 'USA'],
  },
  {
    lat: 15.3694, lng: 44.191,
    name: 'Yemen War',
    country: 'Yemen',
    severity: 7.0,
    type: 'proxy',
    tag: 'yemen',
    casualties: '150,000+',
    startDate: '2015-03-26',
    description: 'Houthi rebellion backed by Iran; Saudi-led coalition intervention.',
    factions: ['Houthis', 'Saudi Coalition', 'STC'],
    relatedCountries: ['Saudi Arabia', 'Iran', 'UAE', 'USA'],
  },
  {
    lat: 23.5, lng: 120.96,
    name: 'Taiwan Strait Tensions',
    country: 'Taiwan',
    severity: 7.5,
    type: 'tension',
    tag: 'taiwan',
    startDate: '1949-10-01',
    description: 'PRC military exercises; US-Taiwan security cooperation; risk of conflict.',
    factions: ['PRC', 'Taiwan', 'USA'],
    relatedCountries: ['Japan', 'Philippines', 'Australia'],
  },
  {
    lat: 37.5665, lng: 127.978,
    name: 'Korean Peninsula',
    country: 'North Korea',
    severity: 6.5,
    type: 'tension',
    tag: 'korea',
    description: 'DPRK missile tests; Russia-DPRK military cooperation; heightened tensions.',
    factions: ['DPRK', 'ROK', 'USA'],
    relatedCountries: ['China', 'Russia', 'Japan'],
  },
  {
    lat: 34.5553, lng: 69.2075,
    name: 'Afghanistan Insurgency',
    country: 'Afghanistan',
    severity: 6.5,
    type: 'insurgency',
    tag: 'iran',
    description: 'Taliban governance; IS-K terror attacks; humanitarian collapse.',
    factions: ['Taliban', 'IS-K', 'NRF'],
    relatedCountries: ['Pakistan', 'Iran', 'Russia', 'China'],
  },
  {
    lat: 16.8661, lng: -3.0026,
    name: 'Sahel Insurgency',
    country: 'Mali',
    severity: 7.0,
    type: 'insurgency',
    tag: 'sahel',
    description: 'JNIM and IS-GS expanding; military juntas; Wagner Group / Africa Corps.',
    factions: ['JNIM', 'IS-GS', 'Wagner/Africa Corps'],
    relatedCountries: ['France', 'Russia', 'Burkina Faso', 'Niger'],
  },
  {
    lat: -1.5, lng: 29.5,
    name: 'Eastern DRC Crisis',
    country: 'DR Congo',
    severity: 7.5,
    type: 'proxy',
    tag: 'drc',
    casualties: '6M+ displaced',
    startDate: '1996-01-01',
    description: 'M23 (Rwanda-backed) advance; FDLR and 100+ armed groups active.',
    factions: ['M23/RDF', 'FARDC', 'FDLR'],
    relatedCountries: ['Rwanda', 'Uganda', 'Angola', 'UN'],
  },
  {
    lat: 9.145, lng: 40.4897,
    name: 'Ethiopia Conflicts',
    country: 'Ethiopia',
    severity: 6.0,
    type: 'insurgency',
    tag: 'ethiopia',
    description: 'Amhara and Oromia insurgencies post-Tigray war ceasefire.',
    factions: ['ENDF', 'Fano', 'OLA'],
    relatedCountries: ['Eritrea', 'Sudan', 'Somalia'],
  },
  {
    lat: 21.0, lng: 96.5,
    name: 'Myanmar Civil War',
    country: 'Myanmar',
    severity: 8.0,
    type: 'civil-war',
    tag: 'myanmar',
    startDate: '2021-02-01',
    description: 'Military junta vs resistance forces; Brotherhood Alliance offensive.',
    factions: ['SAC', 'PDF', '3BHA', 'MNDAA'],
    relatedCountries: ['China', 'Thailand', 'India'],
  },
  {
    lat: 35.0, lng: 45.0,
    name: 'Iran–Israel Shadow War',
    country: 'Iran',
    severity: 8.0,
    type: 'proxy',
    tag: 'iran',
    description: 'Direct missile exchanges; proxy network in Lebanon, Syria, Iraq, Yemen.',
    factions: ['Iran/IRGC', 'Israel/IDF', 'Axis of Resistance'],
    relatedCountries: ['USA', 'Saudi Arabia', 'Iraq', 'Syria'],
  },
  {
    lat: 34.6937, lng: 135.5022,
    name: 'Russia–NATO Cyber Domain',
    country: 'Global',
    severity: 7.0,
    type: 'cyber',
    tag: 'ukraine',
    description: 'Ongoing cyber operations; infrastructure attacks; disinformation campaigns.',
    factions: ['GRU', 'NATO CCDCOE'],
    relatedCountries: ['Estonia', 'Poland', 'Germany', 'UK'],
  },
];

// ── Conflict Tag → keyword mapping for RSS classification ─────────────
export const TAG_KEYWORDS: Record<ConflictTag, string[]> = {
  ukraine: ['ukraine', 'zelensky', 'kyiv', 'donbas', 'kherson', 'bakhmut', 'zaporizhzhia'],
  russia: ['russia', 'putin', 'kremlin', 'moscow', 'wagner', 'russian army'],
  gaza: ['gaza', 'hamas', 'rafah', 'idf', 'west bank', 'ceasefire', 'hostage', 'netanyahu'],
  israel: ['israel', 'jerusalem', 'tel aviv', 'idf', 'mossad', 'knesset'],
  taiwan: ['taiwan', 'taipei', 'tsai', 'strait', 'pla exercises'],
  china: ['china', 'beijing', 'xi jinping', 'south china sea', 'prc', 'pla'],
  iran: ['iran', 'tehran', 'irgc', 'khamenei', 'nuclear program', 'sanctions'],
  sudan: ['sudan', 'rsf', 'khartoum', 'darfur', 'saf', 'hemeti'],
  myanmar: ['myanmar', 'burma', 'junta', 'tatmadaw', 'sac', 'aung san suu kyi'],
  yemen: ['yemen', 'houthi', 'sanaa', 'aden', 'saudi coalition'],
  sahel: ['mali', 'burkina faso', 'niger', 'jnim', 'sahel', 'jihadist', 'africa corps'],
  drc: ['congo', 'drc', 'm23', 'kinshasa', 'goma', 'kivu'],
  korea: ['north korea', 'kim jong', 'dprk', 'icbm', 'pyongyang', 'south korea'],
  kashmir: ['kashmir', 'pakistan india', 'loc', 'islamabad'],
  ethiopia: ['ethiopia', 'addis ababa', 'tigray', 'amhara', 'fano', 'oromia'],
  libya: ['libya', 'tripoli', 'benghazi', 'haftar', 'gna'],
  lebanon: ['lebanon', 'hezbollah', 'beirut', 'nasrallah', 'southern lebanon'],
  iraq: ['iraq', 'baghdad', 'isis', 'pmu', 'kataib hezbollah'],
  syria: ['syria', 'damascus', 'assad', 'idlib', 'hts'],
  nato: ['nato', 'article 5', 'alliance', 'stoltenberg', 'pentagon'],
  nuclear: ['nuclear', 'warhead', 'icbm', 'deterrence', 'non-proliferation', 'npt'],
  cyber: ['cyberattack', 'hack', 'ransomware', 'infrastructure attack', 'disinformation'],
  economy: ['sanctions', 'oil price', 'grain', 'commodity', 'inflation', 'supply chain'],
  diplomacy: ['ceasefire', 'peace talks', 'un security council', 'negotiation', 'mediati'],
  humanitarian: ['refugee', 'displaced', 'famine', 'aid', 'unicef', 'unhcr', 'msf'],
};

// ── Sentiment keywords ────────────────────────────────────────────────
export const NEGATIVE_WORDS = ['attack', 'killed', 'war', 'bomb', 'missile', 'death', 'explosion', 'strike', 'invasion', 'massacre', 'siege', 'collapse', 'crisis', 'conflict', 'troops', 'escalat', 'casualties', 'threat', 'retaliat', 'offensive', 'sanction', 'detention'];
export const POSITIVE_WORDS = ['ceasefire', 'peace', 'agreement', 'deal', 'withdraw', 'diplomatic', 'negotiat', 'aid', 'relief', 'talks', 'cooperat', 'alliance'];

// ── Region mapping ────────────────────────────────────────────────────
export const TAG_TO_REGION: Record<ConflictTag, Region> = {
  ukraine: 'Eastern Europe',
  russia: 'Eastern Europe',
  gaza: 'Middle East',
  israel: 'Middle East',
  taiwan: 'East Asia',
  china: 'East Asia',
  iran: 'Middle East',
  sudan: 'Africa',
  myanmar: 'Southeast Asia',
  yemen: 'Middle East',
  sahel: 'Africa',
  drc: 'Africa',
  korea: 'East Asia',
  kashmir: 'South Asia',
  ethiopia: 'Africa',
  libya: 'Middle East',
  lebanon: 'Middle East',
  iraq: 'Middle East',
  syria: 'Middle East',
  nato: 'Eastern Europe',
  nuclear: 'Global',
  cyber: 'Global',
  economy: 'Global',
  diplomacy: 'Global',
  humanitarian: 'Global',
};

// ── Color scheme ──────────────────────────────────────────────────────
export const SEVERITY_COLORS = (s: number): string => {
  if (s >= 9) return '#ff0000';
  if (s >= 7.5) return '#ff4400';
  if (s >= 6) return '#ff8800';
  if (s >= 4) return '#ffcc00';
  return '#44aa66';
};

export const REGION_COLORS: Record<string, string> = {
  'Eastern Europe': '#ff4400',
  'Middle East': '#ff8800',
  'East Asia': '#ffcc00',
  'Africa': '#ff6622',
  'Southeast Asia': '#aa4400',
  'South Asia': '#ff9933',
  'Americas': '#4466ff',
  'Central Asia': '#aa8800',
  'Global': '#888888',
};
